FROM python:3.11-slim
WORKDIR /app
RUN pip install --no-cache-dir \
    streamlit \
    pandas \
    plotly \
    streamlit-authenticator \
    hdfs \
    requests \
    streamlit-shadcn-ui \
    streamlit-extras \
    streamlit-aggrid \
    st-chat-message \
    streamlit-feedback
COPY app/ /app
EXPOSE 8501
CMD ["streamlit", "run", "cji_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
