"""fetch_fonts.py — download Source Serif 4 + Inter WOFF2 for self-hosting (MIL-136).

Spec (panel 2026-04-26 Reichenstein + Kravets):
    Source Serif 4 — headings, display, citations
    Inter          — body, UI, forms

Why self-host: cjipro.com is reached on Barclays / HSBC / Lloyds corp
networks where Google Fonts CDN can be blocked or flagged. Self-hosted at
cjipro.com/fonts/ keeps every byte under our domain.

How: this script asks Google Fonts CSS endpoint for the @font-face block
with a modern-Chrome User-Agent (so we get WOFF2 not TTF), filters down to
latin + latin-ext unicode ranges (English banking deployment — no cyrillic /
vietnamese / greek needed), downloads each .woff2 to mil/publish/site/fonts/,
and rewrites the @font-face URLs to local /fonts/<file>.woff2 paths.

Fonts are OFL-licensed; redistribution is explicitly allowed by the licence.
We bundle OFL.txt next to the woff2 files to keep that note visible.

Run:
    py mil/publish/fonts_pipeline/fetch_fonts.py
    py mil/publish/fonts_pipeline/fetch_fonts.py --check  # verify present, no fetch

Outputs:
    mil/publish/site/fonts/<font>-<weight>-<subset>.woff2
    mil/publish/site/fonts/fonts.css
    mil/publish/site/fonts/OFL.txt
"""
from __future__ import annotations

import argparse
import re
import sys
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent.parent
OUT_DIR = REPO / "mil" / "publish" / "site" / "fonts"

# Latin + latin-ext only. The Google Fonts CSS gives us each unicode-range
# block annotated as a comment; we keep only the two we need.
KEEP_SUBSETS = {"latin", "latin-ext"}

# Chrome UA so Google returns WOFF2 (older UAs get TTF).
UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/120.0.0.0 Safari/537.36"
)

GOOGLE_CSS_URL = (
    "https://fonts.googleapis.com/css2"
    "?family=Inter:wght@400;500;700"
    "&family=Source+Serif+4:wght@400;700"
    "&display=swap"
)

OFL_LICENSE_TEXT = """\
Both Source Serif 4 and Inter are licensed under the SIL Open Font Licence
(OFL) version 1.1. The full licence text is at https://openfontlicense.org.

Source Serif 4 © Adobe, contributors. https://github.com/adobe-fonts/source-serif
Inter           © Rasmus Andersson, contributors. https://github.com/rsms/inter

Redistribution of the unmodified font binaries (as bundled here, fetched
from Google Fonts CDN at build time) is explicitly permitted by the OFL.
"""


def _fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=20) as resp:  # noqa: S310 — pinned URL
        return resp.read()


def _parse_blocks(css: str) -> list[dict]:
    """Split the Google Fonts CSS into one record per @font-face block.

    Each block is preceded by `/* <subset> */` and contains a font-family,
    font-weight, src, and unicode-range. We capture all four.
    """
    pattern = re.compile(
        r"/\*\s*([\w-]+)\s*\*/\s*@font-face\s*\{([^}]+)\}",
        re.DOTALL,
    )
    blocks: list[dict] = []
    for m in pattern.finditer(css):
        subset = m.group(1).strip()
        body = m.group(2)

        family_m = re.search(r"font-family:\s*'([^']+)'", body)
        weight_m = re.search(r"font-weight:\s*(\d+)", body)
        src_m = re.search(r"src:\s*url\(([^)]+)\)\s*format\('woff2'\)", body)
        urange_m = re.search(r"unicode-range:\s*([^;]+);", body)

        if not (family_m and weight_m and src_m and urange_m):
            continue

        blocks.append({
            "subset": subset,
            "family": family_m.group(1),
            "weight": int(weight_m.group(1)),
            "src_url": src_m.group(1).strip(),
            "unicode_range": urange_m.group(1).strip(),
        })
    return blocks


def _local_filename(family: str, weight: int, subset: str) -> str:
    family_slug = family.lower().replace(" ", "-")
    return f"{family_slug}-{weight}-{subset}.woff2"


def _build_css(blocks: list[dict]) -> str:
    """Re-emit the @font-face rules with local /fonts/<file>.woff2 URLs."""
    lines: list[str] = [
        "/* AUTO-GENERATED by mil/publish/fonts_pipeline/fetch_fonts.py.",
        " * MIL-136 — self-hosted Source Serif 4 + Inter (OFL).",
        " * Edit fetch_fonts.py + re-run if the font set changes. */",
        "",
    ]
    for b in blocks:
        local = _local_filename(b["family"], b["weight"], b["subset"])
        lines.append("@font-face {")
        lines.append(f'  font-family: "{b["family"]}";')
        lines.append(f"  font-style: normal;")
        lines.append(f"  font-weight: {b['weight']};")
        lines.append(f"  font-display: swap;")
        lines.append(f'  src: url("/fonts/{local}") format("woff2");')
        lines.append(f"  unicode-range: {b['unicode_range']};")
        lines.append("}")
    return "\n".join(lines) + "\n"


def fetch_all() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    print(f"[1/4] Fetching CSS index from Google Fonts...")
    css = _fetch(GOOGLE_CSS_URL).decode("utf-8")

    blocks = _parse_blocks(css)
    blocks = [b for b in blocks if b["subset"] in KEEP_SUBSETS]
    if not blocks:
        print("ERROR: no latin / latin-ext @font-face blocks parsed", file=sys.stderr)
        return 1
    print(f"[2/4] Parsed {len(blocks)} @font-face blocks (latin + latin-ext)")

    print(f"[3/4] Downloading WOFF2 files to {OUT_DIR.relative_to(REPO)}...")
    total_bytes = 0
    for b in blocks:
        local = _local_filename(b["family"], b["weight"], b["subset"])
        dest = OUT_DIR / local
        if dest.exists():
            total_bytes += dest.stat().st_size
            print(f"    skip   {local}  (already present, {dest.stat().st_size} bytes)")
            continue
        data = _fetch(b["src_url"])
        dest.write_bytes(data)
        total_bytes += len(data)
        print(f"    write  {local}  ({len(data)} bytes)")

    print(f"[4/4] Writing fonts.css + OFL.txt")
    (OUT_DIR / "fonts.css").write_bytes(_build_css(blocks).encode("utf-8"))
    (OUT_DIR / "OFL.txt").write_bytes(OFL_LICENSE_TEXT.encode("utf-8"))
    print(f"\nOK — {len(blocks)} woff2 files, {total_bytes} bytes total ({total_bytes // 1024} KB)")
    return 0


def check_only() -> int:
    """Verify expected files exist (used as a build-time sanity check)."""
    missing: list[str] = []
    for name in ("fonts.css", "OFL.txt"):
        if not (OUT_DIR / name).exists():
            missing.append(name)
    if not OUT_DIR.exists() or not any(OUT_DIR.glob("*.woff2")):
        missing.append("*.woff2 (none found)")
    if missing:
        print(f"FAIL: missing in {OUT_DIR.relative_to(REPO)}: {missing}", file=sys.stderr)
        print("Run: py mil/publish/fonts_pipeline/fetch_fonts.py", file=sys.stderr)
        return 1
    woff_count = sum(1 for _ in OUT_DIR.glob("*.woff2"))
    print(f"OK — fonts.css present + {woff_count} woff2 files in {OUT_DIR.relative_to(REPO)}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--check", action="store_true", help="Verify presence, no fetch")
    args = parser.parse_args()
    if args.check:
        return check_only()
    return fetch_all()


if __name__ == "__main__":
    sys.exit(main())
